<a href="https://colab.research.google.com/github/Yanem-G/ML_projects/blob/master/Customer_churn_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import random
from sklearn.model_selection import train_test_split,KFold
import tensorflow as tf
from tensorflow.keras import Sequential,models,layers
from tensorflow.keras.layers import Dense,Input,Dropout
from tensorflow.keras.losses import binary_crossentropy
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import AUC
from sklearn.utils import class_weight
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score,classification_report

In [ ]:
df = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

df.head()

,Customer_ID,Age,Gender,Location,Subscription_Type,Account_Age_Months,Monthly_Spending,Total_Usage_Hours,Support_Calls,Late_Payments,Streaming_Usage,Discount_Used,Satisfaction_Score,Last_Interaction_Type,Complaint_Tickets,Promo_Opted_In,Churn
0,1001,19,Male,Illinois,Basic,50,152.44,416,5,2,61,76,3,Neutral,0,1,1
1,1002,41,Male,California,Premium,14,113.34,36,5,1,17,90,5,Negative,3,0,0
2,1003,44,Female,Florida,Basic,2,168.39,207,3,1,85,12,6,Neutral,3,0,1
3,1004,21,Male,Florida,Basic,55,197.12,379,4,3,54,32,4,Positive,3,1,0
4,1005,65,Male,New York,Premium,12,84.46,475,5,4,82,62,1,Neutral,0,0,1

In [ ]:
# drop the noise features found in the EDA

#df = df.drop(["Gender","Location","Age","Last_Interaction_Type","Satisfaction_Score","Streaming_Usage"],axis=1)
#test = test.drop(["Gender","Location","Age","Last_Interaction_Type","Satisfaction_Score","Streaming_Usage"],axis=1)

In [ ]:
df = df.drop('Customer_ID',axis=1)
test = test.drop('Customer_ID',axis=1)

In [ ]:
# feature engineering : using signal features to create meaningful features

df["Usage_rate"] = df["Total_Usage_Hours"]/df["Account_Age_Months"]
df["Support_calls_rate"] = df["Support_Calls"]/df["Account_Age_Months"]
df["Spending_per_hour"] = df["Monthly_Spending"]/df["Total_Usage_Hours"]

test["Usage_rate"] = test["Total_Usage_Hours"]/test["Account_Age_Months"]
test["Support_calls_rate"] = test["Support_Calls"]/test["Account_Age_Months"]
test["Spending_per_hour"] = test["Monthly_Spending"]/test["Total_Usage_Hours"]

# using the new features with the original ones
df["Support_effecency"] = df["Support_calls_rate"]/(df["Complaint_Tickets"] + 1)

test["Support_effecency"] = test["Support_calls_rate"]/(test["Complaint_Tickets"] + 1)

In [ ]:
#one hot encoding

df = pd.get_dummies(data=df,columns=["Location"],dtype=int,drop_first=True)
df = pd.get_dummies(data=df,columns=["Subscription_Type"],dtype=int,drop_first=True)
test = pd.get_dummies(data=test,columns=["Location"],dtype=int,drop_first=True)
test = pd.get_dummies(data=test,columns=["Subscription_Type"],dtype=int,drop_first=True)
test["Gender"] = test["Gender"].replace({"Male" : 0,"Female" : 1})
df["Gender"] = df["Gender"].replace({"Male" : 0,"Female" : 1})
test["Last_Interaction_Type"] = test["Last_Interaction_Type"].replace({"Negative" : 0,"Neutral" : 1,"Positive" : 2})
df["Last_Interaction_Type"] = df["Last_Interaction_Type"].replace({"Negative" : 0,"Neutral" : 1,"Positive" : 2})

/tmp/ipykernel_2246/2399801256.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test["Gender"] = test["Gender"].replace({"Male" : 0,"Female" : 1})
/tmp/ipykernel_2246/2399801256.py:8: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Gender"] = df["Gender"].replace({"Male" : 0,"Female" : 1})
/tmp/ipykernel_2246/2399801256.py:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test["Last_Interaction_Type"] = test["Last_Interaction_Type"].replace({"Negative" : 0,"Neutral" : 1,"Positive" : 2})
/tmp/ipykernel_2246/2399801256.py:10: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Last_Interaction_Type"] = df["Last_Interaction_Type"].replace({"Negative" : 0,"Neutral" : 1,"Positive" : 2})

In [ ]:
df.head()

,Age,Gender,Account_Age_Months,Monthly_Spending,Total_Usage_Hours,Support_Calls,Late_Payments,Streaming_Usage,Discount_Used,Satisfaction_Score,...,Usage_rate,Support_calls_rate,Spending_per_hour,Support_effecency,Location_Florida,Location_Illinois,Location_New York,Location_Texas,Subscription_Type_Enterprise,Subscription_Type_Premium
0,19,0,50,152.44,416,5,2,61,76,3,...,8.320000,0.100000,0.366442,0.100000,0,1,0,0,0,0
1,41,0,14,113.34,36,5,1,17,90,5,...,2.571429,0.357143,3.148333,0.089286,0,0,0,0,0,1
2,44,1,2,168.39,207,3,1,85,12,6,...,103.500000,1.500000,0.813478,0.375000,1,0,0,0,0,0
3,21,0,55,197.12,379,4,3,54,32,4,...,6.890909,0.072727,0.520106,0.018182,1,0,0,0,0,0
4,65,0,12,84.46,475,5,4,82,62,1,...,39.583333,0.416667,0.177811,0.416667,0,0,1,0,0,1

In [ ]:
# check if there is any Non-numeric columns
for col in df.columns:
    if not pd.api.types.is_numeric_dtype(df[col]):
        print(f"Non-numeric column: {col}")

In [ ]:
x = df.drop(["Churn"],axis=1)
y = df["Churn"]
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,stratify=y)

In [ ]:
x_train.shape

(6400, 23)

In [ ]:
#we will randomize the hyper parameters
options={
    "num_of_layers":[2,3],
    "num_of_units":[32,64],
}

def select_hyper_par(options):
    num_of_units=[]
    num_of_layers = random.choice(options["num_of_layers"])
    for i in range(num_of_layers):
        num_of_units.append(random.choice(options["num_of_units"]))

    return{
        "num_of_layers":num_of_layers,
        "num_of_units":num_of_units,
    }
#build model
def build_model(options):
    model = Sequential()
    model.add(Input(shape=(23,)))
    for units in options["num_of_units"]:
        model.add(Dense(units=units , activation='relu'))
        model.add(Dropout(0.3))
    model.add(Dense(units=1 , activation='sigmoid'))
    return model

In [ ]:
#define number of fold for k-CV
k=5
kf=KFold(n_splits=k,shuffle=True,random_state=42)

In [ ]:
# checking if the output data are imbalance
print(y_train.value_counts(normalize=True))

Churn
0    0.686875
1    0.313125
Name: proportion, dtype: float64

In [ ]:
# balance the weight of the output prediction, to prevent the model from choosing only churn = 0 and ignoring churn = 1 because they are fewer than the first
weights = class_weight.compute_class_weight(
    'balanced',
    classes=np.unique(y_train),
    y=y_train
)

class_weight_dict = {0: weights[0], 1: weights[1]}
def Random_Search(n_iteration):
    best_score=0.5
    for i in range(n_iteration):
        average_auc=[]
        param=select_hyper_par(options)
        for train_idx,val_idx in kf.split(x_train):
            #train and val are arrays we can use them in indexing in numpy !!!
            x_cv_train, x_cv_test= x_train.iloc[train_idx], x_train.iloc[val_idx]
            y_cv_train, y_cv_test= y_train.iloc[train_idx], y_train.iloc[val_idx]
            #scaling cross validation data
            scaler = StandardScaler()
            x_cv_train = scaler.fit_transform(x_cv_train)
            x_cv_test= scaler.transform(x_cv_test)

            model = build_model(param)
            model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),loss = binary_crossentropy,metrics=['accuracy',AUC(name='auc')])
            early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)
            model.fit(x_cv_train,y_cv_train,epochs=10,validation_data=(x_cv_test,y_cv_test),class_weight=class_weight_dict,callbacks=[early_stop],batch_size=32,verbose=0)
            # results = [loss, accuracy, auc]
            results = model.evaluate(x_cv_test,y_cv_test,verbose=0)
            #AUC measures how well your model can distinguish between class 0 and class 1. A score of 0.5 is a random guess, and 1.0 is a perfect model.
            auc = results[2]
            average_auc.append(auc)

        current_score=np.mean(average_auc)
        if current_score>best_score:
            best_score=current_score
            best_params=param
    return best_params,best_score
best_params,best_score = Random_Search(20)
print(f"best average accuracy:{best_score}")
print(f"best hyperparameters is {best_params}")

best average accuracy:0.5165137052536011
best hyperparameters is {'num_of_layers': 2, 'num_of_units': [32, 64]}


best average accuracy:0.5220126926898956
best hyperparameters is {'num_of_layers': 3, 'num_of_units': [32, 64, 64]}

In [ ]:
# final scaling
final_scaler = StandardScaler()
x_train = final_scaler.fit_transform(x_train)
x_test = final_scaler.transform(x_test)

In [ ]:

#we're going to use early stopping to see when the accuracy start decreasing
early_stop = EarlyStopping(monitor='val_auc', patience=10, restore_best_weights=True)
best_model = build_model({'num_of_layers': 3, 'num_of_units': [32, 64, 64]})
best_model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),loss = binary_crossentropy,metrics=['accuracy',AUC(name='auc')])

# Using validation_split as requested to provide metrics for the early stopper
best_model.fit(x_train, y_train, epochs=200, validation_split=0.2,class_weight=class_weight_dict ,callbacks=[early_stop], batch_size=32)

Epoch 1/200
160/160 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - accuracy: 0.4992 - auc: 0.4981 - loss: 0.7147 - val_accuracy: 0.5586 - val_auc: 0.5182 - val_loss: 0.6883
Epoch 2/200
160/160 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.4900 - auc: 0.5036 - loss: 0.7028 - val_accuracy: 0.3820 - val_auc: 0.5280 - val_loss: 0.7098
Epoch 3/200
160/160 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.5121 - auc: 0.5196 - loss: 0.6986 - val_accuracy: 0.4086 - val_auc: 0.5300 - val_loss: 0.7027
Epoch 4/200
160/160 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.5047 - auc: 0.5150 - loss: 0.6968 - val_accuracy: 0.4516 - val_auc: 0.5296 - val_loss: 0.6996
Epoch 5/200
160/160 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.4906 - auc: 0.5173 - loss: 0.6957 - val_accuracy: 0.4273 - val_auc: 0.5137 - val_loss: 0.6997
Epoch 6/200
160/160 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.4879 - auc: 0.5249 - loss: 0.6942 - val_accuracy: 0.5680 - val_auc: 0.5207 - val_loss: 0.6887
Epoch 7/200
160/160 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.4945 - auc: 0.5156 - loss: 0.6955 - val_accuracy: 0.5188 - val_auc: 0.5264 - val_loss: 0.6916
Epoch 8/200
160/160 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.4873 - auc: 0.5210 - loss: 0.6949 - val_accuracy: 0.5984 - val_auc: 0.5459 - val_loss: 0.6852
Epoch 9/200
160/160 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.5076 - auc: 0.5154 - loss: 0.6956 - val_accuracy: 0.4563 - val_auc: 0.5249 - val_loss: 0.6958
Epoch 10/200
160/160 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.4824 - auc: 0.5239 - loss: 0.6943 - val_accuracy: 0.5063 - val_auc: 0.5304 - val_loss: 0.6923
Epoch 11/200
160/160 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.5314 - auc: 0.5321 - loss: 0.6944 - val_accuracy: 0.3852 - val_auc: 0.5225 - val_loss: 0.7040
Epoch 12/200
160/160 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.4855 - auc: 0.5419 - loss: 0.6918 - val_accuracy: 0.4672 - val_auc: 0.5239 - val_loss: 0.6958
Epoch 13/200
160/160 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5197 - auc: 0.5401 - loss: 0.6930 - val_accuracy: 0.4242 - val_auc: 0.5232 - val_loss: 0.7011
Epoch 14/200
160/160 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.5115 - auc: 0.5446 - loss: 0.6922 - val_accuracy: 0.4477 - val_auc: 0.5298 - val_loss: 0.6977
Epoch 15/200
160/160 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.4988 - auc: 0.5510 - loss: 0.6916 - val_accuracy: 0.4898 - val_auc: 0.5192 - val_loss: 0.6931
Epoch 16/200
160/160 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.5221 - auc: 0.5498 - loss: 0.6916 - val_accuracy: 0.4352 - val_auc: 0.5146 - val_loss: 0.7024
Epoch 17/200
160/160 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.5150 - auc: 0.5616 - loss: 0.6890 - val_accuracy: 0.4391 - val_auc: 0.5139 - val_loss: 0.7016
Epoch 18/200
160/160 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.5203 - auc: 0.5473 - loss: 0.6916 - val_accuracy: 0.4375 - val_auc: 0.5176 - val_loss: 0.7015

In [ ]:
predictions = (best_model.predict(x_test) > 0.5).astype(int)

50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [ ]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.69      0.67      0.68      1099
           1       0.32      0.34      0.33       501

    accuracy                           0.57      1600
   macro avg       0.50      0.50      0.50      1600
weighted avg       0.57      0.57      0.57      1600

In [ ]:
# check how many times the model predict "churn" and "no churn"
y_pred = (best_model.predict(x_test) > 0.5).astype(int)
print(np.unique(y_pred, return_counts=True))

50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
(array([0, 1]), array([687, 913]))


##When:

- Data is imbalanced

- Class weights used

- Model slightly underfits

###The natural decision boundary is rarely 0.5.